events {}

http {
  resolver 127.0.0.11 valid=10s ipv6=off;

  server {
    listen 8081;

    location = /stub_status {
      stub_status;
      access_log off;
    }
  }

  server {
    listen 5000;

    location = /health {
      default_type application/json;
      return 200 '{"status":"ok"}';
    }

    location = /health/creation {
      set $creation_backend http://creation:5001;
      proxy_pass $creation_backend/health;
    }

    location = /health/redirect {
      set $redirect_backend http://redirect:5002;
      proxy_pass $redirect_backend/health;
    }

    location = /urls {
      error_page 418 = @not_found;
      if ($request_method != POST) {
        return 418;
      }
      set $creation_backend http://creation:5001;
      proxy_pass $creation_backend/urls;
    }

    location ~ "^/[0-9A-Za-z]{7}$" {
      set $redirect_backend http://redirect:5002;
      proxy_pass $redirect_backend;
    }

    location / {
      try_files "" @not_found;
    }

    location @not_found {
      default_type application/json;
      return 404 '{"error":{"code":"SHORT_URL_NOT_FOUND","message":"Short URL not found."}}';
    }
  }
}
