events {}

http {
  server {
    listen 5000;

    location = /health {
      default_type application/json;
      return 200 '{"status":"ok"}';
    }

    location = /health/creation {
      proxy_pass http://creation:5001/health;
    }

    location = /health/redirect {
      proxy_pass http://redirect:5002/health;
    }

    location = /urls {
      error_page 418 = @not_found;
      if ($request_method != POST) {
        return 418;
      }
      proxy_pass http://creation:5001/urls;
    }

    location ~ "^/[0-9A-Za-z]{7}$" {
      proxy_pass http://redirect:5002;
    }

    location / {
      try_files "" @not_found;
    }

    location @not_found {
      default_type application/json;
      return 404 '{"error":{"code":"SHORT_URL_NOT_FOUND","message":"Short URL not found."}}';
    }
  }
}
