CREATE TABLE urls (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  short_code VARCHAR(7) NOT NULL UNIQUE,
  original_url TEXT NOT NULL,
  normalized_url TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
